#pragma once

#include <cstdint>
#include <cstddef>
#include <span>
#include <vector>

struct SNES_SPC;
struct SPC_Filter;

namespace snesquik::apu {

class Apu {
public:
    Apu();
    ~Apu();

    Apu(const Apu&) = delete;
    Apu& operator=(const Apu&) = delete;

    void init();
    void reset();
    void softReset();

    uint8_t readPort(int port);
    void writePort(int port, uint8_t data);

    void step(uint32_t cpuCycles);
    void endFrame();

    // Stereo samples (interleaved L/R) generated by the frame that just
    // ended. Valid until the next endFrame().
    std::span<const int16_t> frameSamples() const;

    void saveState(std::vector<uint8_t>& out);
    bool loadState(const uint8_t* data, size_t size);

    // Debug introspection
    int debugPc() const;
    const char* debugError() const;
    int debugRam(int addr) const;
    int debugOutPort(int port) const;
    int debugInPort(int port) const;

    static constexpr int clockRate = 1024000;
    static constexpr int sampleRate = 32000;
    static constexpr uint64_t masterClockRate = 21477272;

private:
    void armOutputBuffer();

    // ~534 stereo pairs per 60 Hz frame; leave generous headroom for long
    // frames and carried-over samples.
    static constexpr int sampleBufferSize = 4096;

    SNES_SPC* spc = nullptr;
    SPC_Filter* filter = nullptr;
    uint64_t spcTimeAccum = 0;
    uint32_t spcTime = 0;
    int16_t sampleBuffer[sampleBufferSize] = {};
    int16_t outputSamples[sampleBufferSize] = {};
    int outputSampleCount = 0;
};

} // namespace snesquik::apu
