#pragma once

#include <cstdint>
#include <cstddef>
#include <span>
#include <vector>

struct SNES_SPC;
struct SPC_Filter;

namespace snesquik::apu {

class Apu {
public:
    Apu();
    ~Apu();

    Apu(const Apu&) = delete;
    Apu& operator=(const Apu&) = delete;

    void init();
    void reset();
    void softReset();

    uint8_t readPort(int port);
    void writePort(int port, uint8_t data);

    // Advance the SPC700 by a raw delta of CPU cycles. Used as a fallback when
    // no CPU clock is wired in (e.g. unit tests).
    void step(uint32_t cpuCycles);

    // Cycle-accurate path: advance the SPC700 to the absolute CPU cycle count
    // of the access that is about to happen, plus any extra cycles the CPU was
    // halted (e.g. DMA) that are not reflected in its own cycle counter. This
    // is what makes the tight CPU<->SPC port handshake line up at
    // sub-instruction granularity (run the SPC to the exact moment of each
    // $2140-$2143 access before performing it).
    void syncToCpuCycle(uint64_t cpuCycle, uint32_t extraCycles = 0);

    // Re-anchor the CPU-cycle baseline without advancing the SPC. Call after a
    // save-state load so the next sync computes a sane delta.
    void resyncCpuBaseline(uint64_t cpuCycle) { lastCpuCycle = cpuCycle; }

    void endFrame();

    // Stereo samples (interleaved L/R) generated by the frame that just
    // ended. Valid until the next endFrame().
    std::span<const int16_t> frameSamples() const;

    void saveState(std::vector<uint8_t>& out);
    bool loadState(const uint8_t* data, size_t size);

    // Debug introspection
    int debugPc() const;
    const char* debugError() const;
    int debugRam(int addr) const;
    int debugOutPort(int port) const;
    int debugInPort(int port) const;

    static constexpr int clockRate = 1024000;
    static constexpr int sampleRate = 32000;
    static constexpr uint64_t masterClockRate = 21477272;

private:
    void armOutputBuffer();
    void advance(uint32_t cpuCycles);

    // ~534 stereo pairs per 60 Hz frame; leave generous headroom for long
    // frames and carried-over samples.
    static constexpr int sampleBufferSize = 4096;

    SNES_SPC* spc = nullptr;
    SPC_Filter* filter = nullptr;
    uint64_t spcTimeAccum = 0;
    uint32_t spcTime = 0;
    // SPC cycles the SPC has been run AHEAD of the CPU-implied time by the
    // port-handshake consumption gate (run-ahead credit). Future advance()
    // calls consume this before running the SPC, so it never double-advances.
    // Absolute CPU cycle count at the last sync; deltas from this drive the SPC.
    uint64_t lastCpuCycle = 0;
    int16_t sampleBuffer[sampleBufferSize] = {};
    int16_t outputSamples[sampleBufferSize] = {};
    int outputSampleCount = 0;
};

} // namespace snesquik::apu
